export const buttonsArr = new Map<string, string>([
  ["clean", "C"],
  ["sqrt", "√"],
  ["percent", "%"],
  ["division", "/"],
  ["seven", "7"],
  ["eight", "8"],
  ["nine", "9"],
  ["multiply", "×"],
  ["four", "4"],
  ["five", "5"],
  ["six", "6"],
  ["substraction", "-"],
  ["one", "1"],
  ["two", "2"],
  ["three", "3"],
  ["plus", "+"],
  ["double_zero", "00"],
  ["zero", "0"],
  ["comma", ","],
  ["equals", "="],
]);
